apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2026-02-04T19:28:03Z"
  generation: 13
  name: portfolio
  namespace: argocd
  resourceVersion: "29492"
  uid: 6e0d0317-3ffd-4a0c-b2db-80800a4c5e89
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/KavinduGD/portfolio-manifests.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
