apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-pod.yaml
  - frontend-svc.yaml
  - mongodb-ss.yaml
  - mongodb-svc.yaml
  - backend-depl.yaml
  - backend-svc.yaml
  - backend-pvc.yaml
