apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stage-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb

    # Internet-facing ALB
    alb.ingress.kubernetes.io/scheme: internet-facing

    # ALB routes directly to Pod IPs
    alb.ingress.kubernetes.io/target-type: ip

    # Listen on HTTP and HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'

    # ACM certificate for both domains
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:767397975047:certificate/b072abe0-1a80-4d69-b154-d047aabe6371

    # Force HTTP â†’ HTTPS
    alb.ingress.kubernetes.io/ssl-redirect: "443"

spec:
  rules:
    - host: www.kavindu-gihan.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80

    - host: kavindu-gihan.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
